{{ HTML::script('js/jquery.min.js') }}
{{ HTML::script('js/jquery-migrate.js') }}
{{ HTML::script('plugins/jqueryui/jquery-ui.min.js') }}
{{ HTML::script('js/bootstrap.min.js') }}
{{ HTML::script('plugins/moment/moment.min.js') }}
{{ HTML::script('plugins/nprogress/nprogress.js') }}
{{ HTML::script('plugins/nicescroll/jquery.nicescroll.min.js') }}
{{ HTML::script('plugins/perfectscrollbar/perfect-scrollbar.min.js') }}
{{ HTML::script('plugins/datatable/js/jquery.dataTables.min.js') }}
{{ HTML::script('plugins/datatable/js/dataTables.buttons.min.js') }}
{{ HTML::script('plugins/datatable/js/buttons.flash.min.js') }}
{{ HTML::script('plugins/datatable/js/jszip.min.js') }}
{{ HTML::script('plugins/datatable/js/pdfmake.min.js') }}
{{ HTML::script('plugins/datatable/js/vfs_fonts.js') }}
{{ HTML::script('plugins/datatable/js/buttons.html5.min.js') }}
{{ HTML::script('plugins/datatable/js/buttons.print.min.js') }}
{{ HTML::script('plugins/datatable/js/dataTables.select.min.js') }}
{{ HTML::script('plugins/datatable/js/dataTables.rowReorder.min.js') }}
{{ HTML::script('plugins/datatable/js/dataTables.responsive.min.js') }}
{{ HTML::script('plugins/select2/js/select2.full.min.js') }}
{{ HTML::script('plugins/bootstrapnotify/bootstrap-notify.min.js') }}
{{ HTML::script('plugins/bootstrapdatepicker/js/bootstrap-datepicker.min.js') }}
{{ HTML::script('plugins/datetimepicker/jquery.datetimepicker.full.min.js') }}
{{ HTML::script('plugins/jquerygantt/js/jquery.fn.gantt.js') }}
{{ HTML::script('plugins/jqueryconfirm/jquery-confirm.min.js') }}
{{ HTML::script('plugins/screenfull/screenfull.min.js') }}
{{ HTML::script('plugins/passwordgenerator/jquery.jquery-password-generator-plugin.min.js') }}
{{ HTML::script('plugins/mousewheel/jquery.mousewheel.min.js') }}
{{ HTML::script('plugins/counterup/waypoints.js') }}
{{ HTML::script('plugins/counterup/jquery.counterup.js') }}
{{ HTML::script('plugins/chartjs/chart.min.js') }}
{{ HTML::script('plugins/caretjs/jquery.caret.min.js') }}
{{ HTML::script('plugins/atjs/js/jquery.atwho.min.js') }}
{{ HTML::script('plugins/dropzonejs/min/dropzone.min.js') }}
{{ HTML::script('plugins/cropper/cropper.min.js') }}
{{ HTML::script('plugins/html2canvas/html2canvas.min.js') }}
{{ HTML::script('plugins/jspdf/jspdf.min.js') }}
{{ HTML::script('plugins/fullcalendar/fullcalendar.min.js') }}
{{ HTML::script('plugins/jemoji/jemoji.min.js') }}
{{ HTML::script('plugins/ladda/spin.min.js') }}
{{ HTML::script('plugins/ladda/ladda.min.js') }}
{{ HTML::script('plugins/offline/offline.min.js') }}
{{ HTML::script('plugins/jquerykeyframes/jquery.keyframes.min.js') }}
{{ HTML::script('plugins/jqueryuitouch/jquery.ui.touch-punch.min.js') }}
{{ HTML::script('js/app.js') }}
