{{ HTML::style('plugins/jqueryui/jquery-ui.min.css') }}
{{ HTML::style('css/bootstrap.min.css') }}
{{ HTML::style('css/font.css') }}
{{ HTML::style('css/font-awesome.min.css') }}
{{ HTML::style('css/pe-icon-7-stroke.css') }}
{{ HTML::style('css/materialdesignicons.min.css') }}
{{ HTML::style('plugins/nprogress/nprogress.css') }}
{{ HTML::style('plugins/nicescroll/nicescroll.css') }}
{{ HTML::style('plugins/perfectscrollbar/perfect-scrollbar.css') }}
{{ HTML::style('plugins/perfectscrollbar/perfect-scrollbar.custom.css') }}
{{ HTML::style('plugins/datatable/css/jquery.dataTables.min.css') }}
{{ HTML::style('plugins/datatable/css/dataTables.buttons.css') }}
{{ HTML::style('plugins/datatable/css/dataTables.select.css') }}
{{ HTML::style('plugins/datatable/css/rowReorder.dataTables.css') }}
{{ HTML::style('plugins/datatable/css/responsive.dataTables.min.css') }}
{{ HTML::style('plugins/datatable/css/jquery.dataTables.custom.css') }}
{{ HTML::style('plugins/animate/animate.min.css') }}
{{ HTML::style('plugins/animate/animate.custom.css') }}
{{ HTML::style('plugins/select2/css/select2.min.css') }}
{{ HTML::style('plugins/select2/css/select2.custom.css') }}
{{ HTML::style('plugins/bootstrapdatepicker/css/bootstrap-datepicker3.min.css') }}
{{ HTML::style('plugins/bootstrapdatepicker/css/bootstrap-datepicker3.custom.css') }}
{{ HTML::style('plugins/datetimepicker/jquery.datetimepicker.min.css') }}
{{ HTML::style('plugins/datetimepicker/jquery.datetimepicker.custom.css') }}
{{ HTML::style('plugins/jquerygantt/css/gantt.css') }}
{{ HTML::style('plugins/jqueryconfirm/jquery-confirm.min.css') }}
{{ HTML::style('plugins/prettycheckbox/pretty.min.css') }}
{{ HTML::style('plugins/prettycheckbox/pretty.custom.css') }}
{{ HTML::style('plugins/atjs/css/jquery.atwho.min.css') }}
{{ HTML::style('plugins/atjs/css/jquery.atwho.custom.css') }}
{{ HTML::style('plugins/dropzonejs/min/dropzone.min.css') }}
{{ HTML::style('plugins/dropzonejs/dropzone.custom.css') }}
{{ HTML::style('plugins/cropper/cropper.min.css') }}
{{ HTML::style('plugins/cropper/cropper.custom.css') }}
{{ HTML::style('plugins/fullcalendar/fullcalendar.min.css') }}
{{ HTML::style('plugins/fullcalendar/fullcalendar.custom.css') }}
{{ HTML::style('plugins/jemoji/jemoji.min.css') }}
{{ HTML::style('plugins/jemoji/jemoji.custom.css') }}
{{ HTML::style('plugins/ladda/ladda-themeless.min.css') }}
{{ HTML::style('plugins/ladda/ladda.custom.css') }}
{{ HTML::style('plugins/offline/themes/offline-theme-default.css') }}
{{ HTML::style('plugins/offline/themes/offline-language-english.css') }}
{{ HTML::style('css/style.css') }}
